### ISSUE TITLE
ROSE without rose_client_data.dat rose_server_data.dat sse_data_test

### ISSUE THREAD

**Issue by meander-wqh** [HustSecurityLab/ROSE-Experiment#1]
ROSE without rose_client_data.dat rose_server_data.dat sse_data_test

**Comment by dingiso** [comment]
try this https://github.com/jgharehchamani/SSE

**Comment by HustSecurityLab** [comment]
> ROSE without rose_client_data.dat rose_server_data.dat sse_data_test

Hey, I have uploaded a python script in the root directory of this repo, named "generate_dataset_from_records.py." Running this script can generate sse_data_test file.

The other indicated two files rose_client_data.dat rose_server_data.dat are not necessary to run our benchmark. It is generated by the program to save its internal states. Those internal states can then be loaded to avoid repeating encrypting the same data when testing the search performance.

**Comment by meander-wqh** [comment]
Thank you！
